// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/chatroom"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/message"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/roommember"
)

// ChatRoomCreate is the builder for creating a ChatRoom entity.
type ChatRoomCreate struct {
	config
	mutation *ChatRoomMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (crc *ChatRoomCreate) SetName(s string) *ChatRoomCreate {
	crc.mutation.SetName(s)
	return crc
}

// SetIsGroupChat sets the "is_group_chat" field.
func (crc *ChatRoomCreate) SetIsGroupChat(b bool) *ChatRoomCreate {
	crc.mutation.SetIsGroupChat(b)
	return crc
}

// SetNillableIsGroupChat sets the "is_group_chat" field if the given value is not nil.
func (crc *ChatRoomCreate) SetNillableIsGroupChat(b *bool) *ChatRoomCreate {
	if b != nil {
		crc.SetIsGroupChat(*b)
	}
	return crc
}

// SetCreatedAt sets the "created_at" field.
func (crc *ChatRoomCreate) SetCreatedAt(t time.Time) *ChatRoomCreate {
	crc.mutation.SetCreatedAt(t)
	return crc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (crc *ChatRoomCreate) SetNillableCreatedAt(t *time.Time) *ChatRoomCreate {
	if t != nil {
		crc.SetCreatedAt(*t)
	}
	return crc
}

// SetUpdatedAt sets the "updated_at" field.
func (crc *ChatRoomCreate) SetUpdatedAt(t time.Time) *ChatRoomCreate {
	crc.mutation.SetUpdatedAt(t)
	return crc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (crc *ChatRoomCreate) SetNillableUpdatedAt(t *time.Time) *ChatRoomCreate {
	if t != nil {
		crc.SetUpdatedAt(*t)
	}
	return crc
}

// SetID sets the "id" field.
func (crc *ChatRoomCreate) SetID(u uuid.UUID) *ChatRoomCreate {
	crc.mutation.SetID(u)
	return crc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (crc *ChatRoomCreate) SetNillableID(u *uuid.UUID) *ChatRoomCreate {
	if u != nil {
		crc.SetID(*u)
	}
	return crc
}

// AddRoomMemberIDs adds the "room_members" edge to the RoomMember entity by IDs.
func (crc *ChatRoomCreate) AddRoomMemberIDs(ids ...int64) *ChatRoomCreate {
	crc.mutation.AddRoomMemberIDs(ids...)
	return crc
}

// AddRoomMembers adds the "room_members" edges to the RoomMember entity.
func (crc *ChatRoomCreate) AddRoomMembers(r ...*RoomMember) *ChatRoomCreate {
	ids := make([]int64, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return crc.AddRoomMemberIDs(ids...)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (crc *ChatRoomCreate) AddMessageIDs(ids ...uuid.UUID) *ChatRoomCreate {
	crc.mutation.AddMessageIDs(ids...)
	return crc
}

// AddMessages adds the "messages" edges to the Message entity.
func (crc *ChatRoomCreate) AddMessages(m ...*Message) *ChatRoomCreate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return crc.AddMessageIDs(ids...)
}

// Mutation returns the ChatRoomMutation object of the builder.
func (crc *ChatRoomCreate) Mutation() *ChatRoomMutation {
	return crc.mutation
}

// Save creates the ChatRoom in the database.
func (crc *ChatRoomCreate) Save(ctx context.Context) (*ChatRoom, error) {
	crc.defaults()
	return withHooks(ctx, crc.sqlSave, crc.mutation, crc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (crc *ChatRoomCreate) SaveX(ctx context.Context) *ChatRoom {
	v, err := crc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (crc *ChatRoomCreate) Exec(ctx context.Context) error {
	_, err := crc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (crc *ChatRoomCreate) ExecX(ctx context.Context) {
	if err := crc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (crc *ChatRoomCreate) defaults() {
	if _, ok := crc.mutation.IsGroupChat(); !ok {
		v := chatroom.DefaultIsGroupChat
		crc.mutation.SetIsGroupChat(v)
	}
	if _, ok := crc.mutation.CreatedAt(); !ok {
		v := chatroom.DefaultCreatedAt()
		crc.mutation.SetCreatedAt(v)
	}
	if _, ok := crc.mutation.UpdatedAt(); !ok {
		v := chatroom.DefaultUpdatedAt()
		crc.mutation.SetUpdatedAt(v)
	}
	if _, ok := crc.mutation.ID(); !ok {
		v := chatroom.DefaultID()
		crc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (crc *ChatRoomCreate) check() error {
	if _, ok := crc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ChatRoom.name"`)}
	}
	if v, ok := crc.mutation.Name(); ok {
		if err := chatroom.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ChatRoom.name": %w`, err)}
		}
	}
	if _, ok := crc.mutation.IsGroupChat(); !ok {
		return &ValidationError{Name: "is_group_chat", err: errors.New(`ent: missing required field "ChatRoom.is_group_chat"`)}
	}
	if _, ok := crc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChatRoom.created_at"`)}
	}
	if _, ok := crc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ChatRoom.updated_at"`)}
	}
	return nil
}

func (crc *ChatRoomCreate) sqlSave(ctx context.Context) (*ChatRoom, error) {
	if err := crc.check(); err != nil {
		return nil, err
	}
	_node, _spec := crc.createSpec()
	if err := sqlgraph.CreateNode(ctx, crc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	crc.mutation.id = &_node.ID
	crc.mutation.done = true
	return _node, nil
}

func (crc *ChatRoomCreate) createSpec() (*ChatRoom, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatRoom{config: crc.config}
		_spec = sqlgraph.NewCreateSpec(chatroom.Table, sqlgraph.NewFieldSpec(chatroom.FieldID, field.TypeUUID))
	)
	if id, ok := crc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := crc.mutation.Name(); ok {
		_spec.SetField(chatroom.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := crc.mutation.IsGroupChat(); ok {
		_spec.SetField(chatroom.FieldIsGroupChat, field.TypeBool, value)
		_node.IsGroupChat = value
	}
	if value, ok := crc.mutation.CreatedAt(); ok {
		_spec.SetField(chatroom.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := crc.mutation.UpdatedAt(); ok {
		_spec.SetField(chatroom.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := crc.mutation.RoomMembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.RoomMembersTable,
			Columns: []string{chatroom.RoomMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roommember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := crc.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.MessagesTable,
			Columns: []string{chatroom.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChatRoomCreateBulk is the builder for creating many ChatRoom entities in bulk.
type ChatRoomCreateBulk struct {
	config
	err      error
	builders []*ChatRoomCreate
}

// Save creates the ChatRoom entities in the database.
func (crcb *ChatRoomCreateBulk) Save(ctx context.Context) ([]*ChatRoom, error) {
	if crcb.err != nil {
		return nil, crcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(crcb.builders))
	nodes := make([]*ChatRoom, len(crcb.builders))
	mutators := make([]Mutator, len(crcb.builders))
	for i := range crcb.builders {
		func(i int, root context.Context) {
			builder := crcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatRoomMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, crcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, crcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, crcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (crcb *ChatRoomCreateBulk) SaveX(ctx context.Context) []*ChatRoom {
	v, err := crcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (crcb *ChatRoomCreateBulk) Exec(ctx context.Context) error {
	_, err := crcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (crcb *ChatRoomCreateBulk) ExecX(ctx context.Context) {
	if err := crcb.Exec(ctx); err != nil {
		panic(err)
	}
}
