// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/chatroom"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/message"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/predicate"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/roommember"
)

// ChatRoomUpdate is the builder for updating ChatRoom entities.
type ChatRoomUpdate struct {
	config
	hooks    []Hook
	mutation *ChatRoomMutation
}

// Where appends a list predicates to the ChatRoomUpdate builder.
func (cru *ChatRoomUpdate) Where(ps ...predicate.ChatRoom) *ChatRoomUpdate {
	cru.mutation.Where(ps...)
	return cru
}

// SetName sets the "name" field.
func (cru *ChatRoomUpdate) SetName(s string) *ChatRoomUpdate {
	cru.mutation.SetName(s)
	return cru
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cru *ChatRoomUpdate) SetNillableName(s *string) *ChatRoomUpdate {
	if s != nil {
		cru.SetName(*s)
	}
	return cru
}

// SetIsGroupChat sets the "is_group_chat" field.
func (cru *ChatRoomUpdate) SetIsGroupChat(b bool) *ChatRoomUpdate {
	cru.mutation.SetIsGroupChat(b)
	return cru
}

// SetNillableIsGroupChat sets the "is_group_chat" field if the given value is not nil.
func (cru *ChatRoomUpdate) SetNillableIsGroupChat(b *bool) *ChatRoomUpdate {
	if b != nil {
		cru.SetIsGroupChat(*b)
	}
	return cru
}

// SetUpdatedAt sets the "updated_at" field.
func (cru *ChatRoomUpdate) SetUpdatedAt(t time.Time) *ChatRoomUpdate {
	cru.mutation.SetUpdatedAt(t)
	return cru
}

// AddRoomMemberIDs adds the "room_members" edge to the RoomMember entity by IDs.
func (cru *ChatRoomUpdate) AddRoomMemberIDs(ids ...int64) *ChatRoomUpdate {
	cru.mutation.AddRoomMemberIDs(ids...)
	return cru
}

// AddRoomMembers adds the "room_members" edges to the RoomMember entity.
func (cru *ChatRoomUpdate) AddRoomMembers(r ...*RoomMember) *ChatRoomUpdate {
	ids := make([]int64, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cru.AddRoomMemberIDs(ids...)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (cru *ChatRoomUpdate) AddMessageIDs(ids ...uuid.UUID) *ChatRoomUpdate {
	cru.mutation.AddMessageIDs(ids...)
	return cru
}

// AddMessages adds the "messages" edges to the Message entity.
func (cru *ChatRoomUpdate) AddMessages(m ...*Message) *ChatRoomUpdate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return cru.AddMessageIDs(ids...)
}

// Mutation returns the ChatRoomMutation object of the builder.
func (cru *ChatRoomUpdate) Mutation() *ChatRoomMutation {
	return cru.mutation
}

// ClearRoomMembers clears all "room_members" edges to the RoomMember entity.
func (cru *ChatRoomUpdate) ClearRoomMembers() *ChatRoomUpdate {
	cru.mutation.ClearRoomMembers()
	return cru
}

// RemoveRoomMemberIDs removes the "room_members" edge to RoomMember entities by IDs.
func (cru *ChatRoomUpdate) RemoveRoomMemberIDs(ids ...int64) *ChatRoomUpdate {
	cru.mutation.RemoveRoomMemberIDs(ids...)
	return cru
}

// RemoveRoomMembers removes "room_members" edges to RoomMember entities.
func (cru *ChatRoomUpdate) RemoveRoomMembers(r ...*RoomMember) *ChatRoomUpdate {
	ids := make([]int64, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cru.RemoveRoomMemberIDs(ids...)
}

// ClearMessages clears all "messages" edges to the Message entity.
func (cru *ChatRoomUpdate) ClearMessages() *ChatRoomUpdate {
	cru.mutation.ClearMessages()
	return cru
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (cru *ChatRoomUpdate) RemoveMessageIDs(ids ...uuid.UUID) *ChatRoomUpdate {
	cru.mutation.RemoveMessageIDs(ids...)
	return cru
}

// RemoveMessages removes "messages" edges to Message entities.
func (cru *ChatRoomUpdate) RemoveMessages(m ...*Message) *ChatRoomUpdate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return cru.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cru *ChatRoomUpdate) Save(ctx context.Context) (int, error) {
	cru.defaults()
	return withHooks(ctx, cru.sqlSave, cru.mutation, cru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cru *ChatRoomUpdate) SaveX(ctx context.Context) int {
	affected, err := cru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cru *ChatRoomUpdate) Exec(ctx context.Context) error {
	_, err := cru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cru *ChatRoomUpdate) ExecX(ctx context.Context) {
	if err := cru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cru *ChatRoomUpdate) defaults() {
	if _, ok := cru.mutation.UpdatedAt(); !ok {
		v := chatroom.UpdateDefaultUpdatedAt()
		cru.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cru *ChatRoomUpdate) check() error {
	if v, ok := cru.mutation.Name(); ok {
		if err := chatroom.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ChatRoom.name": %w`, err)}
		}
	}
	return nil
}

func (cru *ChatRoomUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatroom.Table, chatroom.Columns, sqlgraph.NewFieldSpec(chatroom.FieldID, field.TypeUUID))
	if ps := cru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cru.mutation.Name(); ok {
		_spec.SetField(chatroom.FieldName, field.TypeString, value)
	}
	if value, ok := cru.mutation.IsGroupChat(); ok {
		_spec.SetField(chatroom.FieldIsGroupChat, field.TypeBool, value)
	}
	if value, ok := cru.mutation.UpdatedAt(); ok {
		_spec.SetField(chatroom.FieldUpdatedAt, field.TypeTime, value)
	}
	if cru.mutation.RoomMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.RoomMembersTable,
			Columns: []string{chatroom.RoomMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roommember.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cru.mutation.RemovedRoomMembersIDs(); len(nodes) > 0 && !cru.mutation.RoomMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.RoomMembersTable,
			Columns: []string{chatroom.RoomMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roommember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cru.mutation.RoomMembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.RoomMembersTable,
			Columns: []string{chatroom.RoomMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roommember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cru.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.MessagesTable,
			Columns: []string{chatroom.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cru.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !cru.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.MessagesTable,
			Columns: []string{chatroom.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cru.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.MessagesTable,
			Columns: []string{chatroom.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatroom.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cru.mutation.done = true
	return n, nil
}

// ChatRoomUpdateOne is the builder for updating a single ChatRoom entity.
type ChatRoomUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatRoomMutation
}

// SetName sets the "name" field.
func (cruo *ChatRoomUpdateOne) SetName(s string) *ChatRoomUpdateOne {
	cruo.mutation.SetName(s)
	return cruo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cruo *ChatRoomUpdateOne) SetNillableName(s *string) *ChatRoomUpdateOne {
	if s != nil {
		cruo.SetName(*s)
	}
	return cruo
}

// SetIsGroupChat sets the "is_group_chat" field.
func (cruo *ChatRoomUpdateOne) SetIsGroupChat(b bool) *ChatRoomUpdateOne {
	cruo.mutation.SetIsGroupChat(b)
	return cruo
}

// SetNillableIsGroupChat sets the "is_group_chat" field if the given value is not nil.
func (cruo *ChatRoomUpdateOne) SetNillableIsGroupChat(b *bool) *ChatRoomUpdateOne {
	if b != nil {
		cruo.SetIsGroupChat(*b)
	}
	return cruo
}

// SetUpdatedAt sets the "updated_at" field.
func (cruo *ChatRoomUpdateOne) SetUpdatedAt(t time.Time) *ChatRoomUpdateOne {
	cruo.mutation.SetUpdatedAt(t)
	return cruo
}

// AddRoomMemberIDs adds the "room_members" edge to the RoomMember entity by IDs.
func (cruo *ChatRoomUpdateOne) AddRoomMemberIDs(ids ...int64) *ChatRoomUpdateOne {
	cruo.mutation.AddRoomMemberIDs(ids...)
	return cruo
}

// AddRoomMembers adds the "room_members" edges to the RoomMember entity.
func (cruo *ChatRoomUpdateOne) AddRoomMembers(r ...*RoomMember) *ChatRoomUpdateOne {
	ids := make([]int64, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cruo.AddRoomMemberIDs(ids...)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (cruo *ChatRoomUpdateOne) AddMessageIDs(ids ...uuid.UUID) *ChatRoomUpdateOne {
	cruo.mutation.AddMessageIDs(ids...)
	return cruo
}

// AddMessages adds the "messages" edges to the Message entity.
func (cruo *ChatRoomUpdateOne) AddMessages(m ...*Message) *ChatRoomUpdateOne {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return cruo.AddMessageIDs(ids...)
}

// Mutation returns the ChatRoomMutation object of the builder.
func (cruo *ChatRoomUpdateOne) Mutation() *ChatRoomMutation {
	return cruo.mutation
}

// ClearRoomMembers clears all "room_members" edges to the RoomMember entity.
func (cruo *ChatRoomUpdateOne) ClearRoomMembers() *ChatRoomUpdateOne {
	cruo.mutation.ClearRoomMembers()
	return cruo
}

// RemoveRoomMemberIDs removes the "room_members" edge to RoomMember entities by IDs.
func (cruo *ChatRoomUpdateOne) RemoveRoomMemberIDs(ids ...int64) *ChatRoomUpdateOne {
	cruo.mutation.RemoveRoomMemberIDs(ids...)
	return cruo
}

// RemoveRoomMembers removes "room_members" edges to RoomMember entities.
func (cruo *ChatRoomUpdateOne) RemoveRoomMembers(r ...*RoomMember) *ChatRoomUpdateOne {
	ids := make([]int64, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cruo.RemoveRoomMemberIDs(ids...)
}

// ClearMessages clears all "messages" edges to the Message entity.
func (cruo *ChatRoomUpdateOne) ClearMessages() *ChatRoomUpdateOne {
	cruo.mutation.ClearMessages()
	return cruo
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (cruo *ChatRoomUpdateOne) RemoveMessageIDs(ids ...uuid.UUID) *ChatRoomUpdateOne {
	cruo.mutation.RemoveMessageIDs(ids...)
	return cruo
}

// RemoveMessages removes "messages" edges to Message entities.
func (cruo *ChatRoomUpdateOne) RemoveMessages(m ...*Message) *ChatRoomUpdateOne {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return cruo.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the ChatRoomUpdate builder.
func (cruo *ChatRoomUpdateOne) Where(ps ...predicate.ChatRoom) *ChatRoomUpdateOne {
	cruo.mutation.Where(ps...)
	return cruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cruo *ChatRoomUpdateOne) Select(field string, fields ...string) *ChatRoomUpdateOne {
	cruo.fields = append([]string{field}, fields...)
	return cruo
}

// Save executes the query and returns the updated ChatRoom entity.
func (cruo *ChatRoomUpdateOne) Save(ctx context.Context) (*ChatRoom, error) {
	cruo.defaults()
	return withHooks(ctx, cruo.sqlSave, cruo.mutation, cruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cruo *ChatRoomUpdateOne) SaveX(ctx context.Context) *ChatRoom {
	node, err := cruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cruo *ChatRoomUpdateOne) Exec(ctx context.Context) error {
	_, err := cruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cruo *ChatRoomUpdateOne) ExecX(ctx context.Context) {
	if err := cruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cruo *ChatRoomUpdateOne) defaults() {
	if _, ok := cruo.mutation.UpdatedAt(); !ok {
		v := chatroom.UpdateDefaultUpdatedAt()
		cruo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cruo *ChatRoomUpdateOne) check() error {
	if v, ok := cruo.mutation.Name(); ok {
		if err := chatroom.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ChatRoom.name": %w`, err)}
		}
	}
	return nil
}

func (cruo *ChatRoomUpdateOne) sqlSave(ctx context.Context) (_node *ChatRoom, err error) {
	if err := cruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatroom.Table, chatroom.Columns, sqlgraph.NewFieldSpec(chatroom.FieldID, field.TypeUUID))
	id, ok := cruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChatRoom.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatroom.FieldID)
		for _, f := range fields {
			if !chatroom.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chatroom.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cruo.mutation.Name(); ok {
		_spec.SetField(chatroom.FieldName, field.TypeString, value)
	}
	if value, ok := cruo.mutation.IsGroupChat(); ok {
		_spec.SetField(chatroom.FieldIsGroupChat, field.TypeBool, value)
	}
	if value, ok := cruo.mutation.UpdatedAt(); ok {
		_spec.SetField(chatroom.FieldUpdatedAt, field.TypeTime, value)
	}
	if cruo.mutation.RoomMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.RoomMembersTable,
			Columns: []string{chatroom.RoomMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roommember.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cruo.mutation.RemovedRoomMembersIDs(); len(nodes) > 0 && !cruo.mutation.RoomMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.RoomMembersTable,
			Columns: []string{chatroom.RoomMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roommember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cruo.mutation.RoomMembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.RoomMembersTable,
			Columns: []string{chatroom.RoomMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roommember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cruo.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.MessagesTable,
			Columns: []string{chatroom.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cruo.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !cruo.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.MessagesTable,
			Columns: []string{chatroom.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cruo.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.MessagesTable,
			Columns: []string{chatroom.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChatRoom{config: cruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatroom.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cruo.mutation.done = true
	return _node, nil
}
