// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/message"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/messageread"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/predicate"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/user"
)

// MessageReadUpdate is the builder for updating MessageRead entities.
type MessageReadUpdate struct {
	config
	hooks    []Hook
	mutation *MessageReadMutation
}

// Where appends a list predicates to the MessageReadUpdate builder.
func (mru *MessageReadUpdate) Where(ps ...predicate.MessageRead) *MessageReadUpdate {
	mru.mutation.Where(ps...)
	return mru
}

// SetMessageID sets the "message_id" field.
func (mru *MessageReadUpdate) SetMessageID(u uuid.UUID) *MessageReadUpdate {
	mru.mutation.SetMessageID(u)
	return mru
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (mru *MessageReadUpdate) SetNillableMessageID(u *uuid.UUID) *MessageReadUpdate {
	if u != nil {
		mru.SetMessageID(*u)
	}
	return mru
}

// SetUserID sets the "user_id" field.
func (mru *MessageReadUpdate) SetUserID(u uuid.UUID) *MessageReadUpdate {
	mru.mutation.SetUserID(u)
	return mru
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (mru *MessageReadUpdate) SetNillableUserID(u *uuid.UUID) *MessageReadUpdate {
	if u != nil {
		mru.SetUserID(*u)
	}
	return mru
}

// SetReadAt sets the "read_at" field.
func (mru *MessageReadUpdate) SetReadAt(t time.Time) *MessageReadUpdate {
	mru.mutation.SetReadAt(t)
	return mru
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (mru *MessageReadUpdate) SetNillableReadAt(t *time.Time) *MessageReadUpdate {
	if t != nil {
		mru.SetReadAt(*t)
	}
	return mru
}

// SetMessage sets the "message" edge to the Message entity.
func (mru *MessageReadUpdate) SetMessage(m *Message) *MessageReadUpdate {
	return mru.SetMessageID(m.ID)
}

// SetUser sets the "user" edge to the User entity.
func (mru *MessageReadUpdate) SetUser(u *User) *MessageReadUpdate {
	return mru.SetUserID(u.ID)
}

// Mutation returns the MessageReadMutation object of the builder.
func (mru *MessageReadUpdate) Mutation() *MessageReadMutation {
	return mru.mutation
}

// ClearMessage clears the "message" edge to the Message entity.
func (mru *MessageReadUpdate) ClearMessage() *MessageReadUpdate {
	mru.mutation.ClearMessage()
	return mru
}

// ClearUser clears the "user" edge to the User entity.
func (mru *MessageReadUpdate) ClearUser() *MessageReadUpdate {
	mru.mutation.ClearUser()
	return mru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mru *MessageReadUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mru.sqlSave, mru.mutation, mru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mru *MessageReadUpdate) SaveX(ctx context.Context) int {
	affected, err := mru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mru *MessageReadUpdate) Exec(ctx context.Context) error {
	_, err := mru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mru *MessageReadUpdate) ExecX(ctx context.Context) {
	if err := mru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mru *MessageReadUpdate) check() error {
	if mru.mutation.MessageCleared() && len(mru.mutation.MessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MessageRead.message"`)
	}
	if mru.mutation.UserCleared() && len(mru.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MessageRead.user"`)
	}
	return nil
}

func (mru *MessageReadUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(messageread.Table, messageread.Columns, sqlgraph.NewFieldSpec(messageread.FieldID, field.TypeUUID))
	if ps := mru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mru.mutation.ReadAt(); ok {
		_spec.SetField(messageread.FieldReadAt, field.TypeTime, value)
	}
	if mru.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messageread.MessageTable,
			Columns: []string{messageread.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mru.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messageread.MessageTable,
			Columns: []string{messageread.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mru.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messageread.UserTable,
			Columns: []string{messageread.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mru.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messageread.UserTable,
			Columns: []string{messageread.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{messageread.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mru.mutation.done = true
	return n, nil
}

// MessageReadUpdateOne is the builder for updating a single MessageRead entity.
type MessageReadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageReadMutation
}

// SetMessageID sets the "message_id" field.
func (mruo *MessageReadUpdateOne) SetMessageID(u uuid.UUID) *MessageReadUpdateOne {
	mruo.mutation.SetMessageID(u)
	return mruo
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (mruo *MessageReadUpdateOne) SetNillableMessageID(u *uuid.UUID) *MessageReadUpdateOne {
	if u != nil {
		mruo.SetMessageID(*u)
	}
	return mruo
}

// SetUserID sets the "user_id" field.
func (mruo *MessageReadUpdateOne) SetUserID(u uuid.UUID) *MessageReadUpdateOne {
	mruo.mutation.SetUserID(u)
	return mruo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (mruo *MessageReadUpdateOne) SetNillableUserID(u *uuid.UUID) *MessageReadUpdateOne {
	if u != nil {
		mruo.SetUserID(*u)
	}
	return mruo
}

// SetReadAt sets the "read_at" field.
func (mruo *MessageReadUpdateOne) SetReadAt(t time.Time) *MessageReadUpdateOne {
	mruo.mutation.SetReadAt(t)
	return mruo
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (mruo *MessageReadUpdateOne) SetNillableReadAt(t *time.Time) *MessageReadUpdateOne {
	if t != nil {
		mruo.SetReadAt(*t)
	}
	return mruo
}

// SetMessage sets the "message" edge to the Message entity.
func (mruo *MessageReadUpdateOne) SetMessage(m *Message) *MessageReadUpdateOne {
	return mruo.SetMessageID(m.ID)
}

// SetUser sets the "user" edge to the User entity.
func (mruo *MessageReadUpdateOne) SetUser(u *User) *MessageReadUpdateOne {
	return mruo.SetUserID(u.ID)
}

// Mutation returns the MessageReadMutation object of the builder.
func (mruo *MessageReadUpdateOne) Mutation() *MessageReadMutation {
	return mruo.mutation
}

// ClearMessage clears the "message" edge to the Message entity.
func (mruo *MessageReadUpdateOne) ClearMessage() *MessageReadUpdateOne {
	mruo.mutation.ClearMessage()
	return mruo
}

// ClearUser clears the "user" edge to the User entity.
func (mruo *MessageReadUpdateOne) ClearUser() *MessageReadUpdateOne {
	mruo.mutation.ClearUser()
	return mruo
}

// Where appends a list predicates to the MessageReadUpdate builder.
func (mruo *MessageReadUpdateOne) Where(ps ...predicate.MessageRead) *MessageReadUpdateOne {
	mruo.mutation.Where(ps...)
	return mruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mruo *MessageReadUpdateOne) Select(field string, fields ...string) *MessageReadUpdateOne {
	mruo.fields = append([]string{field}, fields...)
	return mruo
}

// Save executes the query and returns the updated MessageRead entity.
func (mruo *MessageReadUpdateOne) Save(ctx context.Context) (*MessageRead, error) {
	return withHooks(ctx, mruo.sqlSave, mruo.mutation, mruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mruo *MessageReadUpdateOne) SaveX(ctx context.Context) *MessageRead {
	node, err := mruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mruo *MessageReadUpdateOne) Exec(ctx context.Context) error {
	_, err := mruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mruo *MessageReadUpdateOne) ExecX(ctx context.Context) {
	if err := mruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mruo *MessageReadUpdateOne) check() error {
	if mruo.mutation.MessageCleared() && len(mruo.mutation.MessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MessageRead.message"`)
	}
	if mruo.mutation.UserCleared() && len(mruo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MessageRead.user"`)
	}
	return nil
}

func (mruo *MessageReadUpdateOne) sqlSave(ctx context.Context) (_node *MessageRead, err error) {
	if err := mruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(messageread.Table, messageread.Columns, sqlgraph.NewFieldSpec(messageread.FieldID, field.TypeUUID))
	id, ok := mruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MessageRead.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, messageread.FieldID)
		for _, f := range fields {
			if !messageread.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != messageread.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mruo.mutation.ReadAt(); ok {
		_spec.SetField(messageread.FieldReadAt, field.TypeTime, value)
	}
	if mruo.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messageread.MessageTable,
			Columns: []string{messageread.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mruo.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messageread.MessageTable,
			Columns: []string{messageread.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mruo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messageread.UserTable,
			Columns: []string{messageread.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mruo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messageread.UserTable,
			Columns: []string{messageread.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MessageRead{config: mruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{messageread.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	mruo.mutation.done = true
	return _node, nil
}
