// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/message"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/messagereaction"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/user"
)

// MessageReaction is the model entity for the MessageReaction schema.
type MessageReaction struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// メッセージID
	MessageID uuid.UUID `json:"message_id,omitempty"`
	// リアクションしたユーザーID
	UserID uuid.UUID `json:"user_id,omitempty"`
	// リアクション絵文字
	Emoji string `json:"emoji,omitempty"`
	// リアクション作成日時
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MessageReactionQuery when eager-loading is set.
	Edges        MessageReactionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MessageReactionEdges holds the relations/edges for other nodes in the graph.
type MessageReactionEdges struct {
	// Message holds the value of the message edge.
	Message *Message `json:"message,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MessageOrErr returns the Message value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MessageReactionEdges) MessageOrErr() (*Message, error) {
	if e.Message != nil {
		return e.Message, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: message.Label}
	}
	return nil, &NotLoadedError{edge: "message"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MessageReactionEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MessageReaction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case messagereaction.FieldEmoji:
			values[i] = new(sql.NullString)
		case messagereaction.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case messagereaction.FieldID, messagereaction.FieldMessageID, messagereaction.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MessageReaction fields.
func (mr *MessageReaction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case messagereaction.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				mr.ID = *value
			}
		case messagereaction.FieldMessageID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field message_id", values[i])
			} else if value != nil {
				mr.MessageID = *value
			}
		case messagereaction.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				mr.UserID = *value
			}
		case messagereaction.FieldEmoji:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field emoji", values[i])
			} else if value.Valid {
				mr.Emoji = value.String
			}
		case messagereaction.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				mr.CreatedAt = value.Time
			}
		default:
			mr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MessageReaction.
// This includes values selected through modifiers, order, etc.
func (mr *MessageReaction) Value(name string) (ent.Value, error) {
	return mr.selectValues.Get(name)
}

// QueryMessage queries the "message" edge of the MessageReaction entity.
func (mr *MessageReaction) QueryMessage() *MessageQuery {
	return NewMessageReactionClient(mr.config).QueryMessage(mr)
}

// QueryUser queries the "user" edge of the MessageReaction entity.
func (mr *MessageReaction) QueryUser() *UserQuery {
	return NewMessageReactionClient(mr.config).QueryUser(mr)
}

// Update returns a builder for updating this MessageReaction.
// Note that you need to call MessageReaction.Unwrap() before calling this method if this MessageReaction
// was returned from a transaction, and the transaction was committed or rolled back.
func (mr *MessageReaction) Update() *MessageReactionUpdateOne {
	return NewMessageReactionClient(mr.config).UpdateOne(mr)
}

// Unwrap unwraps the MessageReaction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (mr *MessageReaction) Unwrap() *MessageReaction {
	_tx, ok := mr.config.driver.(*txDriver)
	if !ok {
		panic("ent: MessageReaction is not a transactional entity")
	}
	mr.config.driver = _tx.drv
	return mr
}

// String implements the fmt.Stringer.
func (mr *MessageReaction) String() string {
	var builder strings.Builder
	builder.WriteString("MessageReaction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", mr.ID))
	builder.WriteString("message_id=")
	builder.WriteString(fmt.Sprintf("%v", mr.MessageID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", mr.UserID))
	builder.WriteString(", ")
	builder.WriteString("emoji=")
	builder.WriteString(mr.Emoji)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(mr.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MessageReactions is a parsable slice of MessageReaction.
type MessageReactions []*MessageReaction
