// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/message"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/messagereaction"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/predicate"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/user"
)

// MessageReactionQuery is the builder for querying MessageReaction entities.
type MessageReactionQuery struct {
	config
	ctx         *QueryContext
	order       []messagereaction.OrderOption
	inters      []Interceptor
	predicates  []predicate.MessageReaction
	withMessage *MessageQuery
	withUser    *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MessageReactionQuery builder.
func (mrq *MessageReactionQuery) Where(ps ...predicate.MessageReaction) *MessageReactionQuery {
	mrq.predicates = append(mrq.predicates, ps...)
	return mrq
}

// Limit the number of records to be returned by this query.
func (mrq *MessageReactionQuery) Limit(limit int) *MessageReactionQuery {
	mrq.ctx.Limit = &limit
	return mrq
}

// Offset to start from.
func (mrq *MessageReactionQuery) Offset(offset int) *MessageReactionQuery {
	mrq.ctx.Offset = &offset
	return mrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mrq *MessageReactionQuery) Unique(unique bool) *MessageReactionQuery {
	mrq.ctx.Unique = &unique
	return mrq
}

// Order specifies how the records should be ordered.
func (mrq *MessageReactionQuery) Order(o ...messagereaction.OrderOption) *MessageReactionQuery {
	mrq.order = append(mrq.order, o...)
	return mrq
}

// QueryMessage chains the current query on the "message" edge.
func (mrq *MessageReactionQuery) QueryMessage() *MessageQuery {
	query := (&MessageClient{config: mrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(messagereaction.Table, messagereaction.FieldID, selector),
			sqlgraph.To(message.Table, message.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, messagereaction.MessageTable, messagereaction.MessageColumn),
		)
		fromU = sqlgraph.SetNeighbors(mrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (mrq *MessageReactionQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: mrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(messagereaction.Table, messagereaction.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, messagereaction.UserTable, messagereaction.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(mrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MessageReaction entity from the query.
// Returns a *NotFoundError when no MessageReaction was found.
func (mrq *MessageReactionQuery) First(ctx context.Context) (*MessageReaction, error) {
	nodes, err := mrq.Limit(1).All(setContextOp(ctx, mrq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{messagereaction.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mrq *MessageReactionQuery) FirstX(ctx context.Context) *MessageReaction {
	node, err := mrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MessageReaction ID from the query.
// Returns a *NotFoundError when no MessageReaction ID was found.
func (mrq *MessageReactionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = mrq.Limit(1).IDs(setContextOp(ctx, mrq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{messagereaction.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mrq *MessageReactionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := mrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MessageReaction entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MessageReaction entity is found.
// Returns a *NotFoundError when no MessageReaction entities are found.
func (mrq *MessageReactionQuery) Only(ctx context.Context) (*MessageReaction, error) {
	nodes, err := mrq.Limit(2).All(setContextOp(ctx, mrq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{messagereaction.Label}
	default:
		return nil, &NotSingularError{messagereaction.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mrq *MessageReactionQuery) OnlyX(ctx context.Context) *MessageReaction {
	node, err := mrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MessageReaction ID in the query.
// Returns a *NotSingularError when more than one MessageReaction ID is found.
// Returns a *NotFoundError when no entities are found.
func (mrq *MessageReactionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = mrq.Limit(2).IDs(setContextOp(ctx, mrq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{messagereaction.Label}
	default:
		err = &NotSingularError{messagereaction.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mrq *MessageReactionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := mrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MessageReactions.
func (mrq *MessageReactionQuery) All(ctx context.Context) ([]*MessageReaction, error) {
	ctx = setContextOp(ctx, mrq.ctx, ent.OpQueryAll)
	if err := mrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MessageReaction, *MessageReactionQuery]()
	return withInterceptors[[]*MessageReaction](ctx, mrq, qr, mrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mrq *MessageReactionQuery) AllX(ctx context.Context) []*MessageReaction {
	nodes, err := mrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MessageReaction IDs.
func (mrq *MessageReactionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if mrq.ctx.Unique == nil && mrq.path != nil {
		mrq.Unique(true)
	}
	ctx = setContextOp(ctx, mrq.ctx, ent.OpQueryIDs)
	if err = mrq.Select(messagereaction.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mrq *MessageReactionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := mrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mrq *MessageReactionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mrq.ctx, ent.OpQueryCount)
	if err := mrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mrq, querierCount[*MessageReactionQuery](), mrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mrq *MessageReactionQuery) CountX(ctx context.Context) int {
	count, err := mrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mrq *MessageReactionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mrq.ctx, ent.OpQueryExist)
	switch _, err := mrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mrq *MessageReactionQuery) ExistX(ctx context.Context) bool {
	exist, err := mrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MessageReactionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mrq *MessageReactionQuery) Clone() *MessageReactionQuery {
	if mrq == nil {
		return nil
	}
	return &MessageReactionQuery{
		config:      mrq.config,
		ctx:         mrq.ctx.Clone(),
		order:       append([]messagereaction.OrderOption{}, mrq.order...),
		inters:      append([]Interceptor{}, mrq.inters...),
		predicates:  append([]predicate.MessageReaction{}, mrq.predicates...),
		withMessage: mrq.withMessage.Clone(),
		withUser:    mrq.withUser.Clone(),
		// clone intermediate query.
		sql:  mrq.sql.Clone(),
		path: mrq.path,
	}
}

// WithMessage tells the query-builder to eager-load the nodes that are connected to
// the "message" edge. The optional arguments are used to configure the query builder of the edge.
func (mrq *MessageReactionQuery) WithMessage(opts ...func(*MessageQuery)) *MessageReactionQuery {
	query := (&MessageClient{config: mrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mrq.withMessage = query
	return mrq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (mrq *MessageReactionQuery) WithUser(opts ...func(*UserQuery)) *MessageReactionQuery {
	query := (&UserClient{config: mrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mrq.withUser = query
	return mrq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MessageID uuid.UUID `json:"message_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MessageReaction.Query().
//		GroupBy(messagereaction.FieldMessageID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mrq *MessageReactionQuery) GroupBy(field string, fields ...string) *MessageReactionGroupBy {
	mrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MessageReactionGroupBy{build: mrq}
	grbuild.flds = &mrq.ctx.Fields
	grbuild.label = messagereaction.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MessageID uuid.UUID `json:"message_id,omitempty"`
//	}
//
//	client.MessageReaction.Query().
//		Select(messagereaction.FieldMessageID).
//		Scan(ctx, &v)
func (mrq *MessageReactionQuery) Select(fields ...string) *MessageReactionSelect {
	mrq.ctx.Fields = append(mrq.ctx.Fields, fields...)
	sbuild := &MessageReactionSelect{MessageReactionQuery: mrq}
	sbuild.label = messagereaction.Label
	sbuild.flds, sbuild.scan = &mrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MessageReactionSelect configured with the given aggregations.
func (mrq *MessageReactionQuery) Aggregate(fns ...AggregateFunc) *MessageReactionSelect {
	return mrq.Select().Aggregate(fns...)
}

func (mrq *MessageReactionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mrq); err != nil {
				return err
			}
		}
	}
	for _, f := range mrq.ctx.Fields {
		if !messagereaction.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mrq.path != nil {
		prev, err := mrq.path(ctx)
		if err != nil {
			return err
		}
		mrq.sql = prev
	}
	return nil
}

func (mrq *MessageReactionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MessageReaction, error) {
	var (
		nodes       = []*MessageReaction{}
		_spec       = mrq.querySpec()
		loadedTypes = [2]bool{
			mrq.withMessage != nil,
			mrq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MessageReaction).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MessageReaction{config: mrq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mrq.withMessage; query != nil {
		if err := mrq.loadMessage(ctx, query, nodes, nil,
			func(n *MessageReaction, e *Message) { n.Edges.Message = e }); err != nil {
			return nil, err
		}
	}
	if query := mrq.withUser; query != nil {
		if err := mrq.loadUser(ctx, query, nodes, nil,
			func(n *MessageReaction, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mrq *MessageReactionQuery) loadMessage(ctx context.Context, query *MessageQuery, nodes []*MessageReaction, init func(*MessageReaction), assign func(*MessageReaction, *Message)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*MessageReaction)
	for i := range nodes {
		fk := nodes[i].MessageID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(message.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "message_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (mrq *MessageReactionQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*MessageReaction, init func(*MessageReaction), assign func(*MessageReaction, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*MessageReaction)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (mrq *MessageReactionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mrq.querySpec()
	_spec.Node.Columns = mrq.ctx.Fields
	if len(mrq.ctx.Fields) > 0 {
		_spec.Unique = mrq.ctx.Unique != nil && *mrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mrq.driver, _spec)
}

func (mrq *MessageReactionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(messagereaction.Table, messagereaction.Columns, sqlgraph.NewFieldSpec(messagereaction.FieldID, field.TypeUUID))
	_spec.From = mrq.sql
	if unique := mrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mrq.path != nil {
		_spec.Unique = true
	}
	if fields := mrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, messagereaction.FieldID)
		for i := range fields {
			if fields[i] != messagereaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if mrq.withMessage != nil {
			_spec.Node.AddColumnOnce(messagereaction.FieldMessageID)
		}
		if mrq.withUser != nil {
			_spec.Node.AddColumnOnce(messagereaction.FieldUserID)
		}
	}
	if ps := mrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mrq *MessageReactionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mrq.driver.Dialect())
	t1 := builder.Table(messagereaction.Table)
	columns := mrq.ctx.Fields
	if len(columns) == 0 {
		columns = messagereaction.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mrq.sql != nil {
		selector = mrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mrq.ctx.Unique != nil && *mrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mrq.predicates {
		p(selector)
	}
	for _, p := range mrq.order {
		p(selector)
	}
	if offset := mrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MessageReactionGroupBy is the group-by builder for MessageReaction entities.
type MessageReactionGroupBy struct {
	selector
	build *MessageReactionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mrgb *MessageReactionGroupBy) Aggregate(fns ...AggregateFunc) *MessageReactionGroupBy {
	mrgb.fns = append(mrgb.fns, fns...)
	return mrgb
}

// Scan applies the selector query and scans the result into the given value.
func (mrgb *MessageReactionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mrgb.build.ctx, ent.OpQueryGroupBy)
	if err := mrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MessageReactionQuery, *MessageReactionGroupBy](ctx, mrgb.build, mrgb, mrgb.build.inters, v)
}

func (mrgb *MessageReactionGroupBy) sqlScan(ctx context.Context, root *MessageReactionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mrgb.fns))
	for _, fn := range mrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mrgb.flds)+len(mrgb.fns))
		for _, f := range *mrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MessageReactionSelect is the builder for selecting fields of MessageReaction entities.
type MessageReactionSelect struct {
	*MessageReactionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mrs *MessageReactionSelect) Aggregate(fns ...AggregateFunc) *MessageReactionSelect {
	mrs.fns = append(mrs.fns, fns...)
	return mrs
}

// Scan applies the selector query and scans the result into the given value.
func (mrs *MessageReactionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mrs.ctx, ent.OpQuerySelect)
	if err := mrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MessageReactionQuery, *MessageReactionSelect](ctx, mrs.MessageReactionQuery, mrs, mrs.inters, v)
}

func (mrs *MessageReactionSelect) sqlScan(ctx context.Context, root *MessageReactionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mrs.fns))
	for _, fn := range mrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
