// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/message"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/messageread"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/user"
)

// MessageReadCreate is the builder for creating a MessageRead entity.
type MessageReadCreate struct {
	config
	mutation *MessageReadMutation
	hooks    []Hook
}

// SetMessageID sets the "message_id" field.
func (mrc *MessageReadCreate) SetMessageID(u uuid.UUID) *MessageReadCreate {
	mrc.mutation.SetMessageID(u)
	return mrc
}

// SetUserID sets the "user_id" field.
func (mrc *MessageReadCreate) SetUserID(u uuid.UUID) *MessageReadCreate {
	mrc.mutation.SetUserID(u)
	return mrc
}

// SetReadAt sets the "read_at" field.
func (mrc *MessageReadCreate) SetReadAt(t time.Time) *MessageReadCreate {
	mrc.mutation.SetReadAt(t)
	return mrc
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (mrc *MessageReadCreate) SetNillableReadAt(t *time.Time) *MessageReadCreate {
	if t != nil {
		mrc.SetReadAt(*t)
	}
	return mrc
}

// SetID sets the "id" field.
func (mrc *MessageReadCreate) SetID(u uuid.UUID) *MessageReadCreate {
	mrc.mutation.SetID(u)
	return mrc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (mrc *MessageReadCreate) SetNillableID(u *uuid.UUID) *MessageReadCreate {
	if u != nil {
		mrc.SetID(*u)
	}
	return mrc
}

// SetMessage sets the "message" edge to the Message entity.
func (mrc *MessageReadCreate) SetMessage(m *Message) *MessageReadCreate {
	return mrc.SetMessageID(m.ID)
}

// SetUser sets the "user" edge to the User entity.
func (mrc *MessageReadCreate) SetUser(u *User) *MessageReadCreate {
	return mrc.SetUserID(u.ID)
}

// Mutation returns the MessageReadMutation object of the builder.
func (mrc *MessageReadCreate) Mutation() *MessageReadMutation {
	return mrc.mutation
}

// Save creates the MessageRead in the database.
func (mrc *MessageReadCreate) Save(ctx context.Context) (*MessageRead, error) {
	mrc.defaults()
	return withHooks(ctx, mrc.sqlSave, mrc.mutation, mrc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mrc *MessageReadCreate) SaveX(ctx context.Context) *MessageRead {
	v, err := mrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mrc *MessageReadCreate) Exec(ctx context.Context) error {
	_, err := mrc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mrc *MessageReadCreate) ExecX(ctx context.Context) {
	if err := mrc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mrc *MessageReadCreate) defaults() {
	if _, ok := mrc.mutation.ReadAt(); !ok {
		v := messageread.DefaultReadAt()
		mrc.mutation.SetReadAt(v)
	}
	if _, ok := mrc.mutation.ID(); !ok {
		v := messageread.DefaultID()
		mrc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mrc *MessageReadCreate) check() error {
	if _, ok := mrc.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message_id", err: errors.New(`ent: missing required field "MessageRead.message_id"`)}
	}
	if _, ok := mrc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "MessageRead.user_id"`)}
	}
	if _, ok := mrc.mutation.ReadAt(); !ok {
		return &ValidationError{Name: "read_at", err: errors.New(`ent: missing required field "MessageRead.read_at"`)}
	}
	if len(mrc.mutation.MessageIDs()) == 0 {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required edge "MessageRead.message"`)}
	}
	if len(mrc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "MessageRead.user"`)}
	}
	return nil
}

func (mrc *MessageReadCreate) sqlSave(ctx context.Context) (*MessageRead, error) {
	if err := mrc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mrc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	mrc.mutation.id = &_node.ID
	mrc.mutation.done = true
	return _node, nil
}

func (mrc *MessageReadCreate) createSpec() (*MessageRead, *sqlgraph.CreateSpec) {
	var (
		_node = &MessageRead{config: mrc.config}
		_spec = sqlgraph.NewCreateSpec(messageread.Table, sqlgraph.NewFieldSpec(messageread.FieldID, field.TypeUUID))
	)
	if id, ok := mrc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := mrc.mutation.ReadAt(); ok {
		_spec.SetField(messageread.FieldReadAt, field.TypeTime, value)
		_node.ReadAt = value
	}
	if nodes := mrc.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messageread.MessageTable,
			Columns: []string{messageread.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MessageID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mrc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messageread.UserTable,
			Columns: []string{messageread.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MessageReadCreateBulk is the builder for creating many MessageRead entities in bulk.
type MessageReadCreateBulk struct {
	config
	err      error
	builders []*MessageReadCreate
}

// Save creates the MessageRead entities in the database.
func (mrcb *MessageReadCreateBulk) Save(ctx context.Context) ([]*MessageRead, error) {
	if mrcb.err != nil {
		return nil, mrcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mrcb.builders))
	nodes := make([]*MessageRead, len(mrcb.builders))
	mutators := make([]Mutator, len(mrcb.builders))
	for i := range mrcb.builders {
		func(i int, root context.Context) {
			builder := mrcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MessageReadMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mrcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mrcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mrcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mrcb *MessageReadCreateBulk) SaveX(ctx context.Context) []*MessageRead {
	v, err := mrcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mrcb *MessageReadCreateBulk) Exec(ctx context.Context) error {
	_, err := mrcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mrcb *MessageReadCreateBulk) ExecX(ctx context.Context) {
	if err := mrcb.Exec(ctx); err != nil {
		panic(err)
	}
}
