// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/message"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/messagereaction"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/predicate"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/user"
)

// MessageReactionUpdate is the builder for updating MessageReaction entities.
type MessageReactionUpdate struct {
	config
	hooks    []Hook
	mutation *MessageReactionMutation
}

// Where appends a list predicates to the MessageReactionUpdate builder.
func (mru *MessageReactionUpdate) Where(ps ...predicate.MessageReaction) *MessageReactionUpdate {
	mru.mutation.Where(ps...)
	return mru
}

// SetMessageID sets the "message_id" field.
func (mru *MessageReactionUpdate) SetMessageID(u uuid.UUID) *MessageReactionUpdate {
	mru.mutation.SetMessageID(u)
	return mru
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (mru *MessageReactionUpdate) SetNillableMessageID(u *uuid.UUID) *MessageReactionUpdate {
	if u != nil {
		mru.SetMessageID(*u)
	}
	return mru
}

// SetUserID sets the "user_id" field.
func (mru *MessageReactionUpdate) SetUserID(u uuid.UUID) *MessageReactionUpdate {
	mru.mutation.SetUserID(u)
	return mru
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (mru *MessageReactionUpdate) SetNillableUserID(u *uuid.UUID) *MessageReactionUpdate {
	if u != nil {
		mru.SetUserID(*u)
	}
	return mru
}

// SetEmoji sets the "emoji" field.
func (mru *MessageReactionUpdate) SetEmoji(s string) *MessageReactionUpdate {
	mru.mutation.SetEmoji(s)
	return mru
}

// SetNillableEmoji sets the "emoji" field if the given value is not nil.
func (mru *MessageReactionUpdate) SetNillableEmoji(s *string) *MessageReactionUpdate {
	if s != nil {
		mru.SetEmoji(*s)
	}
	return mru
}

// SetMessage sets the "message" edge to the Message entity.
func (mru *MessageReactionUpdate) SetMessage(m *Message) *MessageReactionUpdate {
	return mru.SetMessageID(m.ID)
}

// SetUser sets the "user" edge to the User entity.
func (mru *MessageReactionUpdate) SetUser(u *User) *MessageReactionUpdate {
	return mru.SetUserID(u.ID)
}

// Mutation returns the MessageReactionMutation object of the builder.
func (mru *MessageReactionUpdate) Mutation() *MessageReactionMutation {
	return mru.mutation
}

// ClearMessage clears the "message" edge to the Message entity.
func (mru *MessageReactionUpdate) ClearMessage() *MessageReactionUpdate {
	mru.mutation.ClearMessage()
	return mru
}

// ClearUser clears the "user" edge to the User entity.
func (mru *MessageReactionUpdate) ClearUser() *MessageReactionUpdate {
	mru.mutation.ClearUser()
	return mru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mru *MessageReactionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mru.sqlSave, mru.mutation, mru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mru *MessageReactionUpdate) SaveX(ctx context.Context) int {
	affected, err := mru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mru *MessageReactionUpdate) Exec(ctx context.Context) error {
	_, err := mru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mru *MessageReactionUpdate) ExecX(ctx context.Context) {
	if err := mru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mru *MessageReactionUpdate) check() error {
	if mru.mutation.MessageCleared() && len(mru.mutation.MessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MessageReaction.message"`)
	}
	if mru.mutation.UserCleared() && len(mru.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MessageReaction.user"`)
	}
	return nil
}

func (mru *MessageReactionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(messagereaction.Table, messagereaction.Columns, sqlgraph.NewFieldSpec(messagereaction.FieldID, field.TypeUUID))
	if ps := mru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mru.mutation.Emoji(); ok {
		_spec.SetField(messagereaction.FieldEmoji, field.TypeString, value)
	}
	if mru.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messagereaction.MessageTable,
			Columns: []string{messagereaction.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mru.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messagereaction.MessageTable,
			Columns: []string{messagereaction.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mru.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messagereaction.UserTable,
			Columns: []string{messagereaction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mru.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messagereaction.UserTable,
			Columns: []string{messagereaction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{messagereaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mru.mutation.done = true
	return n, nil
}

// MessageReactionUpdateOne is the builder for updating a single MessageReaction entity.
type MessageReactionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageReactionMutation
}

// SetMessageID sets the "message_id" field.
func (mruo *MessageReactionUpdateOne) SetMessageID(u uuid.UUID) *MessageReactionUpdateOne {
	mruo.mutation.SetMessageID(u)
	return mruo
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (mruo *MessageReactionUpdateOne) SetNillableMessageID(u *uuid.UUID) *MessageReactionUpdateOne {
	if u != nil {
		mruo.SetMessageID(*u)
	}
	return mruo
}

// SetUserID sets the "user_id" field.
func (mruo *MessageReactionUpdateOne) SetUserID(u uuid.UUID) *MessageReactionUpdateOne {
	mruo.mutation.SetUserID(u)
	return mruo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (mruo *MessageReactionUpdateOne) SetNillableUserID(u *uuid.UUID) *MessageReactionUpdateOne {
	if u != nil {
		mruo.SetUserID(*u)
	}
	return mruo
}

// SetEmoji sets the "emoji" field.
func (mruo *MessageReactionUpdateOne) SetEmoji(s string) *MessageReactionUpdateOne {
	mruo.mutation.SetEmoji(s)
	return mruo
}

// SetNillableEmoji sets the "emoji" field if the given value is not nil.
func (mruo *MessageReactionUpdateOne) SetNillableEmoji(s *string) *MessageReactionUpdateOne {
	if s != nil {
		mruo.SetEmoji(*s)
	}
	return mruo
}

// SetMessage sets the "message" edge to the Message entity.
func (mruo *MessageReactionUpdateOne) SetMessage(m *Message) *MessageReactionUpdateOne {
	return mruo.SetMessageID(m.ID)
}

// SetUser sets the "user" edge to the User entity.
func (mruo *MessageReactionUpdateOne) SetUser(u *User) *MessageReactionUpdateOne {
	return mruo.SetUserID(u.ID)
}

// Mutation returns the MessageReactionMutation object of the builder.
func (mruo *MessageReactionUpdateOne) Mutation() *MessageReactionMutation {
	return mruo.mutation
}

// ClearMessage clears the "message" edge to the Message entity.
func (mruo *MessageReactionUpdateOne) ClearMessage() *MessageReactionUpdateOne {
	mruo.mutation.ClearMessage()
	return mruo
}

// ClearUser clears the "user" edge to the User entity.
func (mruo *MessageReactionUpdateOne) ClearUser() *MessageReactionUpdateOne {
	mruo.mutation.ClearUser()
	return mruo
}

// Where appends a list predicates to the MessageReactionUpdate builder.
func (mruo *MessageReactionUpdateOne) Where(ps ...predicate.MessageReaction) *MessageReactionUpdateOne {
	mruo.mutation.Where(ps...)
	return mruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mruo *MessageReactionUpdateOne) Select(field string, fields ...string) *MessageReactionUpdateOne {
	mruo.fields = append([]string{field}, fields...)
	return mruo
}

// Save executes the query and returns the updated MessageReaction entity.
func (mruo *MessageReactionUpdateOne) Save(ctx context.Context) (*MessageReaction, error) {
	return withHooks(ctx, mruo.sqlSave, mruo.mutation, mruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mruo *MessageReactionUpdateOne) SaveX(ctx context.Context) *MessageReaction {
	node, err := mruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mruo *MessageReactionUpdateOne) Exec(ctx context.Context) error {
	_, err := mruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mruo *MessageReactionUpdateOne) ExecX(ctx context.Context) {
	if err := mruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mruo *MessageReactionUpdateOne) check() error {
	if mruo.mutation.MessageCleared() && len(mruo.mutation.MessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MessageReaction.message"`)
	}
	if mruo.mutation.UserCleared() && len(mruo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MessageReaction.user"`)
	}
	return nil
}

func (mruo *MessageReactionUpdateOne) sqlSave(ctx context.Context) (_node *MessageReaction, err error) {
	if err := mruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(messagereaction.Table, messagereaction.Columns, sqlgraph.NewFieldSpec(messagereaction.FieldID, field.TypeUUID))
	id, ok := mruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MessageReaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, messagereaction.FieldID)
		for _, f := range fields {
			if !messagereaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != messagereaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mruo.mutation.Emoji(); ok {
		_spec.SetField(messagereaction.FieldEmoji, field.TypeString, value)
	}
	if mruo.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messagereaction.MessageTable,
			Columns: []string{messagereaction.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mruo.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messagereaction.MessageTable,
			Columns: []string{messagereaction.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mruo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messagereaction.UserTable,
			Columns: []string{messagereaction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mruo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messagereaction.UserTable,
			Columns: []string{messagereaction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MessageReaction{config: mruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{messagereaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	mruo.mutation.done = true
	return _node, nil
}
