// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/messageread"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/predicate"
)

// MessageReadDelete is the builder for deleting a MessageRead entity.
type MessageReadDelete struct {
	config
	hooks    []Hook
	mutation *MessageReadMutation
}

// Where appends a list predicates to the MessageReadDelete builder.
func (mrd *MessageReadDelete) Where(ps ...predicate.MessageRead) *MessageReadDelete {
	mrd.mutation.Where(ps...)
	return mrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mrd *MessageReadDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mrd.sqlExec, mrd.mutation, mrd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mrd *MessageReadDelete) ExecX(ctx context.Context) int {
	n, err := mrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mrd *MessageReadDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(messageread.Table, sqlgraph.NewFieldSpec(messageread.FieldID, field.TypeUUID))
	if ps := mrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mrd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mrd.mutation.done = true
	return affected, err
}

// MessageReadDeleteOne is the builder for deleting a single MessageRead entity.
type MessageReadDeleteOne struct {
	mrd *MessageReadDelete
}

// Where appends a list predicates to the MessageReadDelete builder.
func (mrdo *MessageReadDeleteOne) Where(ps ...predicate.MessageRead) *MessageReadDeleteOne {
	mrdo.mrd.mutation.Where(ps...)
	return mrdo
}

// Exec executes the deletion query.
func (mrdo *MessageReadDeleteOne) Exec(ctx context.Context) error {
	n, err := mrdo.mrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{messageread.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mrdo *MessageReadDeleteOne) ExecX(ctx context.Context) {
	if err := mrdo.Exec(ctx); err != nil {
		panic(err)
	}
}
