// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/message"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/messageread"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/user"
)

// MessageRead is the model entity for the MessageRead schema.
type MessageRead struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// メッセージID
	MessageID uuid.UUID `json:"message_id,omitempty"`
	// 既読したユーザーID
	UserID uuid.UUID `json:"user_id,omitempty"`
	// 既読日時
	ReadAt time.Time `json:"read_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MessageReadQuery when eager-loading is set.
	Edges        MessageReadEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MessageReadEdges holds the relations/edges for other nodes in the graph.
type MessageReadEdges struct {
	// Message holds the value of the message edge.
	Message *Message `json:"message,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MessageOrErr returns the Message value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MessageReadEdges) MessageOrErr() (*Message, error) {
	if e.Message != nil {
		return e.Message, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: message.Label}
	}
	return nil, &NotLoadedError{edge: "message"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MessageReadEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MessageRead) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case messageread.FieldReadAt:
			values[i] = new(sql.NullTime)
		case messageread.FieldID, messageread.FieldMessageID, messageread.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MessageRead fields.
func (mr *MessageRead) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case messageread.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				mr.ID = *value
			}
		case messageread.FieldMessageID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field message_id", values[i])
			} else if value != nil {
				mr.MessageID = *value
			}
		case messageread.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				mr.UserID = *value
			}
		case messageread.FieldReadAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field read_at", values[i])
			} else if value.Valid {
				mr.ReadAt = value.Time
			}
		default:
			mr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MessageRead.
// This includes values selected through modifiers, order, etc.
func (mr *MessageRead) Value(name string) (ent.Value, error) {
	return mr.selectValues.Get(name)
}

// QueryMessage queries the "message" edge of the MessageRead entity.
func (mr *MessageRead) QueryMessage() *MessageQuery {
	return NewMessageReadClient(mr.config).QueryMessage(mr)
}

// QueryUser queries the "user" edge of the MessageRead entity.
func (mr *MessageRead) QueryUser() *UserQuery {
	return NewMessageReadClient(mr.config).QueryUser(mr)
}

// Update returns a builder for updating this MessageRead.
// Note that you need to call MessageRead.Unwrap() before calling this method if this MessageRead
// was returned from a transaction, and the transaction was committed or rolled back.
func (mr *MessageRead) Update() *MessageReadUpdateOne {
	return NewMessageReadClient(mr.config).UpdateOne(mr)
}

// Unwrap unwraps the MessageRead entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (mr *MessageRead) Unwrap() *MessageRead {
	_tx, ok := mr.config.driver.(*txDriver)
	if !ok {
		panic("ent: MessageRead is not a transactional entity")
	}
	mr.config.driver = _tx.drv
	return mr
}

// String implements the fmt.Stringer.
func (mr *MessageRead) String() string {
	var builder strings.Builder
	builder.WriteString("MessageRead(")
	builder.WriteString(fmt.Sprintf("id=%v, ", mr.ID))
	builder.WriteString("message_id=")
	builder.WriteString(fmt.Sprintf("%v", mr.MessageID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", mr.UserID))
	builder.WriteString(", ")
	builder.WriteString("read_at=")
	builder.WriteString(mr.ReadAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MessageReads is a parsable slice of MessageRead.
type MessageReads []*MessageRead
