// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/message"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/messagereaction"
	"github.com/hideaki1979/cc-chat-app/apps/api/ent/user"
)

// MessageReactionCreate is the builder for creating a MessageReaction entity.
type MessageReactionCreate struct {
	config
	mutation *MessageReactionMutation
	hooks    []Hook
}

// SetMessageID sets the "message_id" field.
func (mrc *MessageReactionCreate) SetMessageID(u uuid.UUID) *MessageReactionCreate {
	mrc.mutation.SetMessageID(u)
	return mrc
}

// SetUserID sets the "user_id" field.
func (mrc *MessageReactionCreate) SetUserID(u uuid.UUID) *MessageReactionCreate {
	mrc.mutation.SetUserID(u)
	return mrc
}

// SetEmoji sets the "emoji" field.
func (mrc *MessageReactionCreate) SetEmoji(s string) *MessageReactionCreate {
	mrc.mutation.SetEmoji(s)
	return mrc
}

// SetCreatedAt sets the "created_at" field.
func (mrc *MessageReactionCreate) SetCreatedAt(t time.Time) *MessageReactionCreate {
	mrc.mutation.SetCreatedAt(t)
	return mrc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mrc *MessageReactionCreate) SetNillableCreatedAt(t *time.Time) *MessageReactionCreate {
	if t != nil {
		mrc.SetCreatedAt(*t)
	}
	return mrc
}

// SetID sets the "id" field.
func (mrc *MessageReactionCreate) SetID(u uuid.UUID) *MessageReactionCreate {
	mrc.mutation.SetID(u)
	return mrc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (mrc *MessageReactionCreate) SetNillableID(u *uuid.UUID) *MessageReactionCreate {
	if u != nil {
		mrc.SetID(*u)
	}
	return mrc
}

// SetMessage sets the "message" edge to the Message entity.
func (mrc *MessageReactionCreate) SetMessage(m *Message) *MessageReactionCreate {
	return mrc.SetMessageID(m.ID)
}

// SetUser sets the "user" edge to the User entity.
func (mrc *MessageReactionCreate) SetUser(u *User) *MessageReactionCreate {
	return mrc.SetUserID(u.ID)
}

// Mutation returns the MessageReactionMutation object of the builder.
func (mrc *MessageReactionCreate) Mutation() *MessageReactionMutation {
	return mrc.mutation
}

// Save creates the MessageReaction in the database.
func (mrc *MessageReactionCreate) Save(ctx context.Context) (*MessageReaction, error) {
	mrc.defaults()
	return withHooks(ctx, mrc.sqlSave, mrc.mutation, mrc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mrc *MessageReactionCreate) SaveX(ctx context.Context) *MessageReaction {
	v, err := mrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mrc *MessageReactionCreate) Exec(ctx context.Context) error {
	_, err := mrc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mrc *MessageReactionCreate) ExecX(ctx context.Context) {
	if err := mrc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mrc *MessageReactionCreate) defaults() {
	if _, ok := mrc.mutation.CreatedAt(); !ok {
		v := messagereaction.DefaultCreatedAt()
		mrc.mutation.SetCreatedAt(v)
	}
	if _, ok := mrc.mutation.ID(); !ok {
		v := messagereaction.DefaultID()
		mrc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mrc *MessageReactionCreate) check() error {
	if _, ok := mrc.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message_id", err: errors.New(`ent: missing required field "MessageReaction.message_id"`)}
	}
	if _, ok := mrc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "MessageReaction.user_id"`)}
	}
	if _, ok := mrc.mutation.Emoji(); !ok {
		return &ValidationError{Name: "emoji", err: errors.New(`ent: missing required field "MessageReaction.emoji"`)}
	}
	if _, ok := mrc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MessageReaction.created_at"`)}
	}
	if len(mrc.mutation.MessageIDs()) == 0 {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required edge "MessageReaction.message"`)}
	}
	if len(mrc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "MessageReaction.user"`)}
	}
	return nil
}

func (mrc *MessageReactionCreate) sqlSave(ctx context.Context) (*MessageReaction, error) {
	if err := mrc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mrc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	mrc.mutation.id = &_node.ID
	mrc.mutation.done = true
	return _node, nil
}

func (mrc *MessageReactionCreate) createSpec() (*MessageReaction, *sqlgraph.CreateSpec) {
	var (
		_node = &MessageReaction{config: mrc.config}
		_spec = sqlgraph.NewCreateSpec(messagereaction.Table, sqlgraph.NewFieldSpec(messagereaction.FieldID, field.TypeUUID))
	)
	if id, ok := mrc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := mrc.mutation.Emoji(); ok {
		_spec.SetField(messagereaction.FieldEmoji, field.TypeString, value)
		_node.Emoji = value
	}
	if value, ok := mrc.mutation.CreatedAt(); ok {
		_spec.SetField(messagereaction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := mrc.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messagereaction.MessageTable,
			Columns: []string{messagereaction.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MessageID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mrc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messagereaction.UserTable,
			Columns: []string{messagereaction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MessageReactionCreateBulk is the builder for creating many MessageReaction entities in bulk.
type MessageReactionCreateBulk struct {
	config
	err      error
	builders []*MessageReactionCreate
}

// Save creates the MessageReaction entities in the database.
func (mrcb *MessageReactionCreateBulk) Save(ctx context.Context) ([]*MessageReaction, error) {
	if mrcb.err != nil {
		return nil, mrcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mrcb.builders))
	nodes := make([]*MessageReaction, len(mrcb.builders))
	mutators := make([]Mutator, len(mrcb.builders))
	for i := range mrcb.builders {
		func(i int, root context.Context) {
			builder := mrcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MessageReactionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mrcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mrcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mrcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mrcb *MessageReactionCreateBulk) SaveX(ctx context.Context) []*MessageReaction {
	v, err := mrcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mrcb *MessageReactionCreateBulk) Exec(ctx context.Context) error {
	_, err := mrcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mrcb *MessageReactionCreateBulk) ExecX(ctx context.Context) {
	if err := mrcb.Exec(ctx); err != nil {
		panic(err)
	}
}
